disabled_rules:
- trailing_whitespace
- type_name
- force_cast
- variable_name
- trailing_newline

# rules
#- colon
#- control_statement
#- file_length
#- force_cast
#- function_body_length
#- leading_whitespace
#- line_length
#- nesting
#- operator_whitespace
#- return_arrow_whitespace
#- todo
#- trailing_newline
#- variable_name_max_length
#- variable_name_min_length
#- type_body_length
#- variable_name

line_length: 150

excluded: # Lint対象から外すファイルのあるパスを記述
- Pods
- Carthage

# クラスの行数
type_body_length:
- 300 # warning
- 500 # error

variable_name_min_length:
- 3 # warning
- 0 # error

# 変数名の最大文字数
variable_name_max_length:
- 60 # warning
- 80 # error

# 関数の長さ
function_body_length:
- 100 # warning
- 200 # error